version: '3'
services:
    web:
        build: .
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=cargotracker
        volumes:
            - ./data:/var/lib/postgresql/data
